version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t pgweb .
      - run:
          name: Push Docker image to ECR
          command: |
            $(aws ecr get-login --no-include-email --region us-west-2)
            docker tag pgweb:latest <your-ecr-repo-url>:latest
            docker push <your-ecr-repo-url>:latest

workflows:
  build-and-push:
    jobs:
      - build:
          context: aws-ecr
