version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - run:
          name : testing_ubuntu
          command : |
            apt-get update
            apt-get install sudo -y
            apt install docker -y
            sudo docker run hello-world
      - run:
          name: Push Docker image to ECR
          command: |
            $(aws ecr get-login --no-include-email --region us-west-2)
            docker tag pgweb:latest <your-ecr-repo-url>:latest
            docker push <your-ecr-repo-url>:latest

workflows:
  build-and-push:
    jobs:
      - build:
          context: aws-ecr
